# Generated by Django 5.2.5 on 2025-09-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('on_the_way', 'on the way'), ('arrived', 'arrived')], default=''),
        ),
    ]
