# Generated by Django 5.2.5 on 2025-09-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_customer_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
