# Generated by Django 5.2.5 on 2025-09-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_donation_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('rabbit', 'Rabbit')], default='dog', max_length=10),
        ),
    ]
