# Generated by Django 5.2.5 on 2025-09-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donated',
            field=models.IntegerField(max_length=100),
        ),
    ]
